export const tenders = [
  {
    id: 1,
    name: "Road Construction Project",
    description: "Construction of a new highway connecting City A and City B.",
    biddingAmount: "500,000 USD",
    deadline: "2024-09-01",
    contactPerson: "John Doe",
    contactEmail: "john.doe@example.com",
  },
  {
    id: 2,
    name: "School Renovation",
    description: "Renovation of ABC School with modern facilities.",
    biddingAmount: "200,000 USD",
    deadline: "2024-08-08",
    contactPerson: "Jane Smith",
    contactEmail: "jane.smith@example.com",
  },
  {
    id: 3,
    name: "Hospital Expansion",
    description: "Expansion and upgrade of XYZ Hospital to include new wings and state-of-the-art equipment.",
    biddingAmount: "750,000 USD",
    deadline: "2023-10-01",
    contactPerson: "Alice Johnson",
    contactEmail: "alice.johnson@example.com",
  },
  {
    id: 4,
    name: "Office Building Construction",
    description: "Construction of a new office building in the downtown area.",
    biddingAmount: "1,200,000 USD",
    deadline: "2024-11-30",
    contactPerson: "Robert Brown",
    contactEmail: "robert.brown@example.com",
  },
  {
    id: 5,
    name: "Bridge Repair",
    description: "Repair and reinforcement of the existing bridge on River Road.",
    biddingAmount: "300,000 USD",
    deadline: "2024-09-15",
    contactPerson: "Emily Davis",
    contactEmail: "emily.davis@example.com",
  },
  {
    id: 6,
    name: "Library Modernization",
    description: "Modernization of the city library with new technology and facilities.",
    biddingAmount: "400,000 USD",
    deadline: "2024-07-15",
    contactPerson: "Michael Wilson",
    contactEmail: "michael.wilson@example.com",
  },
  {
    id: 7,
    name: "Park Development",
    description: "Development of a new city park with playgrounds, sports facilities, and green spaces.",
    biddingAmount: "600,000 USD",
    deadline: "2024-12-01",
    contactPerson: "Sophia Martinez",
    contactEmail: "sophia.martinez@example.com",
  },
  {
    id: 8,
    name: "Water Treatment Plant Upgrade",
    description: "Upgrade of the existing water treatment plant to improve efficiency and capacity.",
    biddingAmount: "900,000 USD",
    deadline: "2024-11-15",
    contactPerson: "James Anderson",
    contactEmail: "james.anderson@example.com",
  },
  {
    id: 9,
    name: "Airport Terminal Expansion",
    description: "Expansion of the airport terminal to accommodate more passengers and modern facilities.",
    biddingAmount: "1,500,000 USD",
    deadline: "2024-12-30",
    contactPerson: "Olivia Thomas",
    contactEmail: "olivia.thomas@example.com",
  },
  {
    id: 10,
    name: "City Hall Renovation",
    description: "Complete renovation of the historic city hall.",
    biddingAmount: "700,000 USD",
    deadline: "2024-10-05",
    contactPerson: "David Garcia",
    contactEmail: "david.garcia@example.com",
  },
  {
    id: 11,
    name: "Underground Metro Project",
    description: "Construction of an underground metro system across the city.",
    biddingAmount: "2,000,000 USD",
    deadline: "2024-12-25",
    contactPerson: "Mia Rodriguez",
    contactEmail: "mia.rodriguez@example.com",
  },
  {
    id: 12,
    name: "University Expansion",
    description: "Expansion of the university campus with new buildings and facilities.",
    biddingAmount: "1,100,000 USD",
    deadline: "2024-09-20",
    contactPerson: "Benjamin Clark",
    contactEmail: "benjamin.clark@example.com",
  },
  {
    id: 13,
    name: "Solar Power Plant",
    description: "Installation of a solar power plant to provide renewable energy to the city.",
    biddingAmount: "3,000,000 USD",
    deadline: "2023-11-15",
    contactPerson: "Isabella Lewis",
    contactEmail: "isabella.lewis@example.com",
  },
  {
    id: 14,
    name: "Water Supply Network",
    description: "Upgrading the city's water supply network for better efficiency.",
    biddingAmount: "800,000 USD",
    deadline: "2023-09-25",
    contactPerson: "Ethan Walker",
    contactEmail: "ethan.walker@example.com",
  },
  {
    id: 15,
    name: "Airport Security Upgrade",
    description: "Upgrade of the airport's security system with advanced technology.",
    biddingAmount: "1,800,000 USD",
    deadline: "2024-08-22",
    contactPerson: "Chloe Harris",
    contactEmail: "chloe.harris@example.com",
  },
  {
    id: 16,
    name: "High-Speed Rail Project",
    description: "Construction of a high-speed rail line connecting major cities.",
    biddingAmount: "5,000,000 USD",
    deadline: "2024-09-30",
    contactPerson: "Mason Scott",
    contactEmail: "mason.scott@example.com",
  },
  {
    id: 17,
    name: "Waste Management Facility",
    description: "Development of a new waste management facility with recycling capabilities.",
    biddingAmount: "1,000,000 USD",
    deadline: "2023-12-10",
    contactPerson: "Lucas Green",
    contactEmail: "lucas.green@example.com",
  },
  {
    id: 18,
    name: "Public Transportation System",
    description: "Expansion of the city's public transportation system.",
    biddingAmount: "2,500,000 USD",
    deadline: "2024-10-20",
    contactPerson: "Ava Baker",
    contactEmail: "ava.baker@example.com",
  },
  {
    id: 19,
    name: "Seaport Expansion",
    description: "Expansion of the seaport to handle more cargo and ships.",
    biddingAmount: "3,500,000 USD",
    deadline: "2023-09-01",
    contactPerson: "Liam Adams",
    contactEmail: "liam.adams@example.com",
  },
  {
    id: 20,
    name: "Renewable Energy Research Center",
    description: "Construction of a research center dedicated to renewable energy.",
    biddingAmount: "1,500,000 USD",
    deadline: "2024-11-05",
    contactPerson: "Sophia Carter",
    contactEmail: "sophia.carter@example.com",
  },
  {
    id: 21,
    name: "Industrial Park Development",
    description: "Development of a new industrial park on the outskirts of the city.",
    biddingAmount: "4,000,000 USD",
    deadline: "2023-10-15",
    contactPerson: "William Turner",
    contactEmail: "william.turner@example.com",
  },
  {
    id: 22,
    name: "Healthcare Facility Upgrade",
    description: "Upgrade of the healthcare facility with new equipment and services.",
    biddingAmount: "2,200,000 USD",
    deadline: "2024-12-05",
    contactPerson: "Emma Wright",
    contactEmail: "emma.wright@example.com",
  },
  {
    id: 23,
    name: "Green Building Initiative",
    description: "Construction of eco-friendly buildings in the city center.",
    biddingAmount: "1,300,000 USD",
    deadline: "2023-11-20",
    contactPerson: "Olivia King",
    contactEmail: "olivia.king@example.com",
  },
  {
    id: 24,
    name: "Citywide Wi-Fi Project",
    description: "Implementation of free Wi-Fi across the entire city.",
    biddingAmount: "700,000 USD",
    deadline: "2024-09-10",
    contactPerson: "Noah Wright",
    contactEmail: "noah.wright@example.com",
  },
];
